// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svxrfsmoyhkhurxwsohz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2eHJmc21veWhraHVyeHdzb2h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MTc0MjAsImV4cCI6MjA2ODI5MzQyMH0.E8f9pWWz8lztbNc3zaS77TmixSEFNWnNnSOeJXPyr_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});